### ISSUE TITLE
intel flavored `sklearn` as another backend?

### ISSUE THREAD

**Issue by psteinb** [psteinb/c2st#13]
Just stumbled upon this:
https://intel.github.io/scikit-learn-intelex/

**Comment by elcorto** [comment]
I'd stick to supporting classifiers that have a sklearn API and play nice with `sklearn.model_selection.cross_validate()`. If the package above does that, then we don't have to do any work. This would then be as easy as

```py
from c2st.check import c2st
from xgboost import XGBClassifier

c2st(X, Y, clf=XGBClassifier())
```

using all default settings of `XGBClassifier`.

Having said that, I ended up implementing [thin wrappers around skorch and xgboost](https://github.com/elcorto/c2st/tree/feature-support-special-clfs/src/c2st/classifiers) that add sensible defaults and reduce much of the boilerplate code that people would need to write (such as enabling early stopping). They can be used like so:

```py
from c2st.check import c2st
from c2st.classifiers.xgboost import get_clf

c2st(X, Y, clf=get_clf())
```

Those were used in production and tested that way (they also have unit tests) and I'm happy to maintain them. However I'd not implement similar wrappers w/o having used them in production since I think we don't have the resources to support those.
